// Code generated by MockGen. DO NOT EDIT.
// Source: ip_config_controller.go
//
// Generated by this command:
//
//	mockgen -source=ip_config_controller.go -package=controllers -destination=ip_config_controller_mock.go
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	logr "github.com/go-logr/logr"
	v1 "github.com/openshift-kni/lifecycle-agent/api/ipconfig/v1"
	gomock "go.uber.org/mock/gomock"
	controllerruntime "sigs.k8s.io/controller-runtime"
)

// MockIPConfigStageHandler is a mock of IPConfigStageHandler interface.
type MockIPConfigStageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIPConfigStageHandlerMockRecorder
}

// MockIPConfigStageHandlerMockRecorder is the mock recorder for MockIPConfigStageHandler.
type MockIPConfigStageHandlerMockRecorder struct {
	mock *MockIPConfigStageHandler
}

// NewMockIPConfigStageHandler creates a new mock instance.
func NewMockIPConfigStageHandler(ctrl *gomock.Controller) *MockIPConfigStageHandler {
	mock := &MockIPConfigStageHandler{ctrl: ctrl}
	mock.recorder = &MockIPConfigStageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPConfigStageHandler) EXPECT() *MockIPConfigStageHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockIPConfigStageHandler) Handle(ctx context.Context, ipc *v1.IPConfig) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, ipc)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockIPConfigStageHandlerMockRecorder) Handle(ctx, ipc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockIPConfigStageHandler)(nil).Handle), ctx, ipc)
}

// MockIPConfigTwoPhaseStageHandler is a mock of IPConfigTwoPhaseStageHandler interface.
type MockIPConfigTwoPhaseStageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIPConfigTwoPhaseStageHandlerMockRecorder
}

// MockIPConfigTwoPhaseStageHandlerMockRecorder is the mock recorder for MockIPConfigTwoPhaseStageHandler.
type MockIPConfigTwoPhaseStageHandlerMockRecorder struct {
	mock *MockIPConfigTwoPhaseStageHandler
}

// NewMockIPConfigTwoPhaseStageHandler creates a new mock instance.
func NewMockIPConfigTwoPhaseStageHandler(ctrl *gomock.Controller) *MockIPConfigTwoPhaseStageHandler {
	mock := &MockIPConfigTwoPhaseStageHandler{ctrl: ctrl}
	mock.recorder = &MockIPConfigTwoPhaseStageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPConfigTwoPhaseStageHandler) EXPECT() *MockIPConfigTwoPhaseStageHandlerMockRecorder {
	return m.recorder
}

// PostPivot mocks base method.
func (m *MockIPConfigTwoPhaseStageHandler) PostPivot(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPivot", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostPivot indicates an expected call of PostPivot.
func (mr *MockIPConfigTwoPhaseStageHandlerMockRecorder) PostPivot(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPivot", reflect.TypeOf((*MockIPConfigTwoPhaseStageHandler)(nil).PostPivot), ctx, ipc, logger)
}

// PrePivot mocks base method.
func (m *MockIPConfigTwoPhaseStageHandler) PrePivot(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrePivot", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrePivot indicates an expected call of PrePivot.
func (mr *MockIPConfigTwoPhaseStageHandlerMockRecorder) PrePivot(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrePivot", reflect.TypeOf((*MockIPConfigTwoPhaseStageHandler)(nil).PrePivot), ctx, ipc, logger)
}
